### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by ghost** [OpenSID/installer#3]
![image](https://user-images.githubusercontent.com/60428779/83319106-8c738900-a265-11ea-8413-cf3900822ffb.png)
setelah selesai instalasi tampil halaman server error, saya sudah coba instal di php 7.3 dan 5.2 tetep sama error saat migrasi

**Comment by eddieridwan** [comment]
Mohon tidak membuat issue sebelum anda pastikan error ada di script rilis dan bukan di instalasi anda. Untuk langkah pertama harap tanyakan/bahas di https://www.facebook.com/groups/OpenSID/. 

Dalam kasus seperti yg anda alami, selalu lihat dulu error yg ditampilkan di file di folder `logs`.
